export type Kind = 'vessel' | 'event' | 'closure' | 'hold';
export type FitStatus = 'ok' | 'violation' | 'unverified' | 'n/a';
export type IssueType = 'overlap' | 'fit' | 'vessel_double';
export type LengthStatus = 'known' | 'unknown' | 'disputed';

export interface BerthDTO {
  id: string;
  name: string;
  lengthFt: number | null;
  isExclusive: boolean;
  sortOrder: number;
}

export interface VesselDTO {
  id: string;
  name: string;
  lengthFt: number | null;
  lengthStatus: LengthStatus;
  lengthNote: string | null;
  bookingCount?: number;
}

export interface ReservationDTO {
  id: string;
  berthId: string;
  kind: Kind;
  vesselId: string | null;
  vessel: { id: string; name: string; lengthFt: number | null; lengthStatus: string } | null;
  title: string | null;
  startDate: string;
  endDate: string;
  notes: string | null;
  origin: 'legacy' | 'app';
  sourceRef: string | null;
  fitStatus: FitStatus;
  issues: { id: string; type: IssueType; reviewed: boolean }[];
  createdAt: string;
  updatedAt: string;
}

export interface IssueDTO {
  id: string;
  type: IssueType;
  startDate: string;
  endDate: string;
  berthId: string | null;
  reservation: ReservationDTO;
  other: ReservationDTO | null;
  details: Record<string, unknown>;
  reviewedAt: string | null;
  reviewNote: string | null;
}

export interface BerthOption {
  berthId: string;
  berthName: string;
  lengthFt: number | null;
  fit: 'ok' | 'unverified';
}

export interface DateShift {
  startDate: string;
  endDate: string;
  direction: 'earlier' | 'later';
  days: number;
}

export interface Alternatives {
  berths: BerthOption[];
  dateShifts: DateShift[];
}

/** The editable fields of a booking. An id is optional for excluding an edit from conflicts. */
export interface ReservationInput {
  id?: string;
  berthId: string;
  kind: Kind;
  vesselId?: string | null;
  title?: string | null;
  startDate: string;
  endDate: string;
  notes?: string | null;
}

export type Candidate = ReservationInput;
export type BookingInput = ReservationInput;
export type ReservationLike = ReservationInput & { id: string };

export interface PaginatedResponse<T> {
  items: T[];
  nextCursor: string | null;
}

export type ApiErrorCode = 'VALIDATION_ERROR' | 'NOT_FOUND' | 'BERTH_CONFLICT' | 'VESSEL_CONFLICT'
  | 'VESSEL_EXISTS' | 'FIT_VIOLATION' | 'UNASSIGNED_TARGET' | 'INTERNAL';

export interface ApiErrorResponse {
  error: {
    code: ApiErrorCode;
    message: string;
    conflicts?: ReservationDTO[];
    alternatives?: Alternatives;
  };
}

export interface AvailabilityResult {
  berth: BerthDTO;
  status: 'available' | 'too_short' | 'busy' | 'unverified' | 'shared';
  conflicts: ReservationDTO[];
}
export interface AvailabilityResponse { items: AvailabilityResult[] }

export interface DataRange { from: string; to: string }

/** The import report is preserved as generated by the audited Python migration. */
export interface ImportSummary {
  generated_at: string;
  source_file: string | null;
  sheets_parsed: number;
  month_blocks: number;
  carryover_blocks_skipped: number;
  reservations: number;
  reservations_by_kind: Partial<Record<Kind, number>>;
  vessels: number;
  vessels_by_length_status: Partial<Record<LengthStatus, number>>;
  berths: number;
  schedule_issues_by_type: Partial<Record<IssueType, number>>;
  import_issues_by_code: Record<string, number>;
  data_range: DataRange;
  max_span_days: number;
}

export interface MetaResponse {
  dataRange: DataRange;
  importSummary: ImportSummary;
  berths: BerthDTO[];
}

export interface ImportIssueDTO {
  id: number;
  code: string;
  severity: 'info' | 'warn' | 'error';
  sheet: string | null;
  cell: string | null;
  message: string;
  reservationId: string | null;
}

export interface ImportCodeDTO { code: string; count: number }

export interface VesselUpdateResponse {
  vessel: VesselDTO;
  newFitIssues: number;
  clearedFitIssues: number;
}

export type AskIntent = {
  intent: 'search' | 'availability' | 'issues' | 'navigate' | 'unsupported';
  dateFrom?: string;
  dateTo?: string;
  berthIds?: string[];
  vesselQuery?: string;
  kinds?: Kind[];
  lengthFt?: number;
  issueTypes?: IssueType[];
  reason?: string;
};

export interface AskRequest { q: string; today: string; viewedMonth: string }
export interface AskResponse {
  intent: AskIntent['intent'];
  filters: Omit<AskIntent, 'intent'> & { vesselIds?: string[] };
  chips: { key: string; label: string }[];
  source: 'ai' | 'fallback';
  message?: string;
}
